OnlineBookStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineBookStore.Models;

namespace OnlineBookStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

OnlineBookStore/Views/Shared/BookSummary.cshtml
@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model?.Title
            <span class="badge rounded-pill bg-primary text-white" style="float:right">
                <small>@Model?.Price.ToString()</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">
        <ul>
            <li>Publisher: @Model?.Supplier</li>
            <li>Category: @Model?.Category</li>
            <li>Description: @Model?.Description</li>
        </ul>
    </div>
    <form id="@Model?.BookID" asp-page="/Cart" method="post">
        <input type="hidden" asp-for="BookID" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

OnlineBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OBS</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">OBS</div>
                <div class="col-6 navbar-text text-end">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="jumbotron jumbotron-fluid bg-primary">
        <div class="container">
            <h1 class="display-4 justify-content-center text-center text-white">Welcome to OBS!</h1>
            <hr style="border: 2px solid; color: #343a40; width: 250px" />
            <p class="lead justify-content-center text-center text-white">Find any book that you like, we have few selections here!</p>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:navigation-menu />
        </div>
        <div class="col-9">
        @RenderBody()
        </div>
    </div>
</body>
</html>