OnlineBookStore/Models/Cart.cs
namespace OnlineBookStore.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();

        public virtual void AddItem(Book book, int quantity)
        {
            CartLine? line = Lines.Where(b => b.Book.BookID == book.BookID).FirstOrDefault();

            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Book = book,
                    Quantity = quantity
                });
            } else
            {
                line.Quantity += quantity;
            }
        }
        public virtual void RemoveLine(Book book) => Lines.RemoveAll(l => l.Book.BookID == book.BookID);
        public decimal ComputeTotalValue() => Lines.Sum(e => e.Book.Price * e.Quantity);
        public virtual void Clear() => Lines.Clear();
    }
    public class CartLine
    {
        public int CartLineID { get; set; }
        public Book Book { get; set; } = new();
        public int Quantity { get; set; }
    }
}

OnlineBookStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineBookStore.Models;

namespace OnlineBookStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;
        public OrderController(IOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is currently empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", new { orderId = order.OrderID });
            } else
            {
                return View();
            }
        }
    }
}

OnlineBookStore/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnlineBookStore.Infrastructure;
using OnlineBookStore.Models;

namespace OnlineBookStore.Pages
{
    public class CartModel : PageModel
    {
        private IStoreRepository repository;
        public CartModel(IStoreRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; } = "/";
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }
        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book? book = repository.Books.FirstOrDefault(b => b.BookID == bookId);
            if (book != null)
            {
                Cart.AddItem(book, 1);
            }
            return RedirectToPage( new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl => cl.Book.BookID == bookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

OnlineBookStore/Pages/Completed.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OnlineBookStore.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

OnlineBookStore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SportsStore.Pages
{
    public class ErrorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

OnlineBookStore/Pages/Cart.cshtml
@page
@model CartModel

<h2>Your Cart</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Book</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model?.Cart?.Lines ?? Enumerable.Empty<CartLine>())
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Book.Title</td>
                <td class="text-right">@line.Book.Price.ToString("c")</td>
                <td class="text-right">@((line.Quantity * line.Book.Price).ToString("c"))</td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="BookID" value="@line.Book.BookID" />
                        <input type="hidden" name="returnUrl" value="@Model?.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model?.Cart?.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model?.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">
        Checkout
    </a>
</div>

OnlineBookStore/Pages/Completed.cshtml
@page

<div class="text-center">
    <h2>Much appreciate!</h2>
    <p>Thanks for placing the orders #@OrderId</p>
    <p>Your book will be delivered to your location soon.</p>
    <a class="btn btn-primary" asp-controller="Home">Return to Store</a>
</div>

@functions {
    [BindProperty(SupportsGet = true)]
    public string? OrderId { get; set; }
}

OnlineBookStore/Pages/_CartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OBS</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">OBS</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>